// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    throw UnsupportedError('Unsupported platform');
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfdlnCpaFdK_FwZWz7w1gElxOEfOoctKE',
    appId: '1:281420460156:web:9eefa3ab596049d62d19f9',
    messagingSenderId: '281420460156',
    projectId: 'resellahlanding',
    authDomain: 'resellahlanding.firebaseapp.com',
    storageBucket: 'resellahlanding.firebasestorage.app',
    measurementId: 'G-66L6MW0DK0',
  );
}
