name: Deploy to GitHub Page

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.0'
          channel: 'stable'
      
      - name: Enable Flutter Web
        run: flutter config --enable-web
        
      - name: Get dependencies
        run: flutter pub get
        
      - name: Verify Directory Structure
        run: |
          mkdir -p assets/images
          ls -la assets/images || true
          
      - name: Build
        run: |
          # Build Flutter web
          flutter build web --base-href /resellah_landing_welcome_new/
          
          # Create 404 page
          cp build/web/index.html build/web/404.html
          
          # Debug output
          echo "Contents of build/web directory:"
          ls -la build/web
          echo "Contents of build/web/assets directory:"
          ls -la build/web/assets || true
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          force_orphan: true 